version: "3.9"
services:
  fastapi:
    image: ghcr.io/levasuzuki2005/misha_laba5:main
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    networks:
      - app_network


  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./html:/usr/share/nginx/html
    depends_on:
      - fastapi
    restart: always
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
